swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST for Naive bayes model
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

# Paths supported by the server application
paths:
  /preds:
    post:
      operationId: naive_model.phrase_pred
      tags:
        - Text
      summary: mahoe
      description: mahoe2
      parameters:
        - name: body
          in: body
          description: in body
          required: True
          schema:
            type: object
            properties:
              phrases: 
                type: array
                items:
                  type: string
      responses:
        default:
          description: "successful operation"