swagger: "2.0"
info:
  title: Sentiment analysis API
  description: This is a API from sentiment analysis model
  version: "1.0.0"
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

# Paths supported by the server application
paths:
  /preds:
    post:
      operationId: naive_model.phrase_pred
      tags:
        - Sentiment analysis
      summary: Get sentiment from phrase
      description: ""
      parameters:
        - name: body
          in: body
          description: in body
          required: True
          schema:
            type: object
            properties:
              phrases: 
                type: array
                items:
                  type: string
      responses:
        200:
          description: "OK"